[package]
name = "url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tera = "1"
lazy_static = "1.5.0"
rand = "0.8.5"
serde = {version="1.0", features = ["derive"]}
regex = "1.11.1"
